version: '3.4'

services:
  pokersolver:
    image: pokersolver
    build:
      context: .
      args: 
        - NODE_ENV=production
    environment:
      NODE_ENV: development
      PORT: 
    volumes:
      - .:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
    ports:
      - ${PORT-3000}:3000
    restart: unless-stopped